"""Add ai_models and multi_modal fields

Revision ID: 8d0f8eeb7f1b
Revises: f8114a0e35bd
Create Date: 2026-04-06 13:44:54.282722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0f8eeb7f1b'
down_revision: Union[str, None] = 'f8114a0e35bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('task_type', sa.String(length=50), nullable=True))
    op.add_column('scenes', sa.Column('provider_used', sa.String(length=50), nullable=True))
    op.add_column('usage_logs', sa.Column('task_type', sa.String(length=50), nullable=True))
    op.add_column('usage_logs', sa.Column('provider_used', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_logs', 'provider_used')
    op.drop_column('usage_logs', 'task_type')
    op.drop_column('scenes', 'provider_used')
    op.drop_column('scenes', 'task_type')
    # ### end Alembic commands ###
